# Generated by Django 2.2 on 2021-01-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
    ]
