# Generated by Django 2.2 on 2021-01-13 01:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, null=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rent.Category', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, null=True, verbose_name='مسیر آدرس دهی')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('mobile_number', models.CharField(max_length=32, null=True, verbose_name='شماره موبایل')),
                ('home_phone_number', models.CharField(max_length=32, null=True, verbose_name='شماره ثابت')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='آدرس')),
                ('price', models.CharField(max_length=128, null=True, verbose_name='قیمت')),
                ('instant', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='آگهی فوری')),
                ('is_stair', models.BooleanField(blank=True, default=False, null=True, verbose_name='آگهی نردبان')),
                ('is_special', models.BooleanField(default=False, null=True, verbose_name='آگهی ویژه')),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2021, 2, 12, 1, 6, 46, 251396, tzinfo=utc), verbose_name='زمان انقضا')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, null=True, verbose_name='وضعیت')),
                ('rent_type', models.CharField(choices=[('h', 'ساعتی'), ('d', 'روزانه'), ('w', 'هفتگی'), ('m', 'ماهیانه'), ('y', 'سالیانه')], max_length=1, null=True)),
                ('priority', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخته شدن')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آپدیت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_rent', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_rent', to='rent.Category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.City')),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='مورد علاقه')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.State')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/ads-images/%Y-%m-%d/', verbose_name='تصویر')),
                ('rent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rent.Rent')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('comment_text', models.TextField(verbose_name='متن دیدگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخته شدن')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت دیدگاه')),
                ('rent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rent.Rent')),
            ],
            options={
                'verbose_name': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.State', verbose_name='استان'),
        ),
    ]
