# Generated by Django 2.2 on 2021-01-13 01:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20210113_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخته شدن'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 1, 27, 52, 813220, tzinfo=utc), verbose_name='زمان انقضا'),
        ),
    ]
