# Generated by Django 2.2 on 2021-01-14 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_auto_20210114_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 20, 0, 45, 952829, tzinfo=utc), verbose_name='زمان انقضا'),
        ),
    ]
