# Generated by Django 2.2 on 2021-01-14 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_auto_20210114_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 20, 12, 34, 463387, tzinfo=utc), verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='قیمت'),
        ),
    ]
