# Generated by Django 2.2 on 2021-01-17 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_auto_20210114_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 23, 21, 47, 695437), verbose_name='زمان انقضا'),
        ),
    ]
