# Generated by Django 2.2 on 2021-01-19 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_auto_20210119_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 1, 25, 55, 697821), verbose_name='زمان انقضا'),
        ),
    ]
