# Generated by Django 2.2 on 2021-01-28 17:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0016_auto_20210119_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='آدرس ای پی'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ratings',
            field=models.IntegerField(default=0, null=True, verbose_name='امتیاز'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False, null=True, verbose_name='وضعیت دیدگاه'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(null=True, verbose_name='متن دیدگاه'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fullname',
            field=models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 17, 55, 20, 616102), verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='نام استان'),
        ),
    ]
