# Generated by Django 2.2 on 2021-01-28 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_auto_20210128_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 18, 17, 52, 109132), verbose_name='زمان انقضا'),
        ),
    ]
