# Generated by Django 2.2 on 2021-01-28 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0018_auto_20210128_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 18, 20, 47, 984020), verbose_name='زمان انقضا'),
        ),
    ]
