# Generated by Django 2.2 on 2021-01-31 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0021_auto_20210131_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.AlterField(
            model_name='rent',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 19, 20, 11, 748094), verbose_name='زمان انقضا'),
        ),
    ]
