# Generated by Django 2.2 on 2020-10-03 07:58

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('mobile_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره موبایل')),
                ('home_phone_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره موبایل')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/avatars/%Y-%m-%d/', verbose_name='تصویر پروفایل')),
                ('home_address', models.TextField(blank=True, null=True, verbose_name='آدرس خانه')),
                ('birthdate', models.DateField(blank=True, max_length=150, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='شهر')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='سایر اطلاعات')),
                ('is_author', models.BooleanField(default=False, verbose_name='وضعیت نویسندگی')),
                ('is_block', models.BooleanField(default=False, verbose_name='وضعیت بلاک کاربر')),
                ('special_user', models.DateTimeField(default=django.utils.timezone.now, verbose_name='کاربر ویژه تا')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
